version: "3"

services:
  web:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - "api"

  api:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8080:8080
